### PR TITLE
Create test runner for GitHub Actions

### LINKED ISSUE #45: fix travis
Failing - switchto docker?

### PR DESCRIPTION
**Pull request by balhoff**
Fixes #45.

### CODE REVIEW

**Comment by balhoff** [comment]
This seems to fix the issue with regard to running on Travis. It does however print this message:

```
./build-neo-makefile.py -i datasets.json > Makefile-gafs.tmp && mv Makefile-gafs.tmp Makefile-gafs
echo "tests disabled until its easier to run perl on travis"
tests disabled until its easier to run perl on travis
```

So it may not be testing much in practice.

**Comment by balhoff** [comment]
After this we should remove the Travis integration.

**Comment by kltm** [comment]
@balhoff Should we just remove it from this PR to see how it goes? I'm happy to do that and merge if it passes.

**Comment by balhoff** [comment]
Okay, I removed the Travis config.

**Comment by kltm** [comment]
Okay, I think this looks good for me--merging.
I guess we'll see how it works in practice in a couple of weeks, unless we manually trigger the pipeline run before then (as we'll have the power outage next week).

**Pull request merged**
