### PR TITLE
Tweak obo-uris hack to handle hash injected by OBO parser.

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by balhoff** [comment]
The Travis failure is unrelated.

**Comment by kltm** [comment]
Looks good to me.
Is there a ticket that this is against; how will we check to see if this is successful?

**Comment by balhoff** [comment]
> Is there a ticket that this is against; how will we check to see if this is successful?

Good question! No ticket; this is a response to an email from @pgaudet. This will be successful if the NEO ontology contains a term with label "nsp4 Scov2" and its IRI looks like `http://identifiers.org/uniprot/P0DTD1-PRO_0000449622` instead of `http://purl.obolibrary.org/obo/UniProtKB#_P0DTD1-PRO_0000449622`.

Also, when this is loaded in Minerva, [this model](http://noctua.geneontology.org/editor/graph/gomodel:5e72450500004237) should no longer have gene products without labels.

**Comment by kltm** [comment]
For https://github.com/geneontology/neo/issues/66

**Comment by kltm** [comment]
@balhoff 
Okay, I created a ticket for this.
For this PR, is the travis issue new, or has this been an outstanding problem? If we know the tests don't/can't work, we should just remove or disable them (and create a ticket to fix them).

**Comment by kltm** [comment]
Also tagging @cmungall

**Comment by balhoff** [comment]
> For this PR, is the travis issue new, or has this been an outstanding problem? If we know the tests don't/can't work, we should just remove or disable them (and create a ticket to fix them).

Looks like an outstanding problem, I think to do with https://github.com/geneontology/neo/blob/8804d90ab3dd1b7062bda57cb6e5c6ec39e21d5f/.travis.yml#L7-L10

**Comment by balhoff** [comment]
Ticket: #45

**Comment by pgaudet** [comment]
I suppose this cannot be merged because it has errors? I think @vanaukenk and @pmasson55 wanted this for next week's COVID19 presentation - it'd be great if this could get resolved.

**Comment by balhoff** [comment]
I'm going to go ahead and merge (the Travis errors are unrelated). Then we have a few steps to get through, at least:

- build and publish new NEO (@kltm can you remind me how this happens?)
- ensure production Minerva is restarted with new NEO in its terminology triplestore

**Comment by kltm** [comment]
@balhoff (and @vanaukenk ) Just to let you know, I've done an early NEO "release", so if there is anything to pickup when minerva restarts, they will all be restarted Monday morning-ish (PDT).

**Comment by balhoff** [comment]
I took a look inside the new NEO file. The IRIs look good. I did note that there is more than one IRI with label "nsp4 Scov2". @pgaudet @vanaukenk is this expected? (e.g. `http://identifiers.org/uniprot/P0DTD1-PRO_0000449622`, and `http://identifiers.org/uniprot/P0DTC1-PRO_0000449638`). I don't think this question is really related to my change in this PR.

**Pull request merged**
