### PR TITLE
Use new support for prefixes in OBO format

### PR DESCRIPTION
**Pull request by balhoff**
The latest ROBOT includes new OWL API support to make use of prefix definitions in OBO format. This will allow us to get rid of the perl regex hack. This should be a fix for https://github.com/geneontology/noctua/issues/902. Also relates to #84 and #17.

These changes haven't been tested on a full build yet—may need to tweak prefix definitions. Also, the latest ROBOT is required for this to work.

### CODE REVIEW

**Comment by balhoff** [comment]
Noting some problems:
- `TAIR:locus:1005794076` in the generated OBO file needs to become `http://identifiers.org/tair.locus/1005203273`
  - this can't be done with a simple prefix compaction; can the generated OBO be changed?

**Comment by kltm** [comment]
@balhoff Originally, there was a sed command in there doing some filtering, do you mean something like that?

**Comment by balhoff** [comment]
@kltm we used https://github.com/geneontology/neo/blob/master/bin/fix-obo-uris.pl to hack in all the right expansions at the end, and this is supposed to now do it "right". But for TAIR:locus in particular I wonder if we can change the OBO generated from the GPI or GAF to not require a regex replacement that is needed by the transformation above.

**Comment by sierra-moxon** [comment]
> @kltm we used https://github.com/geneontology/neo/blob/master/bin/fix-obo-uris.pl to hack in all the right expansions at the end, and this is supposed to now do it "right". But for TAIR:locus in particular I wonder if we can change the OBO generated from the GPI or GAF to not require a regex replacement that is needed by the transformation above.

e.g. given this GAF line in the TAIR upstream src file:
```
AGI_LocusCode   AT5G01310       APTX    involved_in     GO:0000012      TAIR:Communication:501741973    IBA     PANTHER:PTN000281062|UniProtKB:Q7Z2E3|MGI:MGI:1913658   P       AT5G01310       AT5G01310|APTX|APRATAXIN-like|T10O8.20|T10O8_20 protein taxon:3702      20240215        GOC             TAIR:locus:2179122
```
have the ontobio code replace that TAIR:locus:2179122 with tair.locus:2179122 in the resulting GO-generated GPI? (was just intensively in that code so it seems reasonable to do that, if I am understanding correctly - are these two the only one-offs or is there a list of things we want to rewrite to conform to bioregistry/prefixmaps/etc...?)

**Comment by balhoff** [comment]
@sierra-moxon I think the NEO build is getting the GAF straight from TAIR, so maybe that won't work. Unless we're okay with obtaining this from GO instead of TAIR.

https://github.com/geneontology/neo/blob/5cb9a0dbeb92d4787f849a2a7dc57833845c2b72/Makefile-gafs#L434

Thank you though!

**Comment by sierra-moxon** [comment]
ah ok - makes sense - I checked the go-site/metadata/datasets/tair.yaml but it didn't have a GPI so I assumed that somehow you were grabbing the created GPI, but this makes more sense!

**Comment by balhoff** [comment]
Superseded by #121.

**Pull request closed without merging**
